twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']

when@test:
    twig:
        form_themes: ['bootstrap_5_layout.html.twig']
        strict_variables: true
